apiVersion: v1 
kind: Service
metadata:
  name: petclinic-svc 
  namespace: petclinic
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
  selector:
    app: petclinic
    version: blue